FROM oraclelinux:8.7

RUN yum -y install wget rpm-build gcc gcc-c++ make yum-utils
COPY shim-unsigned-aa64-15.7-1.0.2.el8.src.rpm /
RUN rpm -ivh shim-unsigned-aa64-15.7-1.0.2.el8.src.rpm
RUN yum-builddep -y --enablerepo=* /root/rpmbuild/SPECS/shim-unsigned-aarch64.spec
RUN rpmbuild -bb /root/rpmbuild/SPECS/shim-unsigned-aarch64.spec
COPY shimaa64.efi /
RUN ls -l /
RUN ls -l /root/rpmbuild/RPMS/aarch64
RUN rpm2cpio /root/rpmbuild/RPMS/aarch64/shim-unsigned-aa64-15.7-1.0.2.el8.aarch64.rpm  | cpio -idmv
RUN hexdump -Cv ./usr/share/shim/15.7-1.0.2.el8/aa64/shimaa64.efi > built-aa64.hex
RUN hexdump -Cv /shimaa64.efi > orig-aa64.hex
RUN sha256sum /usr/share/shim/15.7-1.0.2.el8/aa64/shimaa64.efi /shimaa64.efi
RUN diff -u orig-aa64.hex built-aa64.hex
RUN objdump -h /usr/share/shim/15.7-1.0.2.el8/aa64/shimaa64.efi
